AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an EC2 instance with ALB, Auto Scaling Group, and Git clone.

Parameters:
  KeyName:
    Description: Name of the EC2 Key Pair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    Default: "test"

  VPC:
    Description: VPC for the resources
    Type: AWS::EC2::VPC::Id
    Default: vpc-00e0a506e346cd668

  Subnets:
    Description: Subnets for the resources
    Type: List<AWS::EC2::Subnet::Id>
    Default:
      - "subnet-009053380b68eca49"
      - "subnet-01e9ec080ed445e77"
      - "subnet-091b56ee214f3d6a6"

  GitHubRepoURL:
    Description: URL of the public Git repository with the website template
    Type: String
    Default: https://github.com/abhisran/web_temp.git

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp
        - CidrIp: '0.0.0.0/0'
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SecurityGroup
      KeyName: !Ref KeyName
      SubnetId: !Select [0, !Ref Subnets] # Select the first subnet from the list
      ImageId: ami-051f7e7f6c2f40dc1
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -ex
            yum update -y
            yum install -y httpd git
            systemctl start httpd
            systemctl enable httpd
            git clone ${GitHubRepoURL} /var/www/html
