AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFormation template to deploy EC2 instance, ALB, Autoscaling, and Git clone

Parameters:

  KeyName:
    Description: Name of EC2 key pair for SSH access 
    Type: AWS::EC2::KeyPair::KeyName
    Default: "test"  # <--- You can change this default value

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
    Default: vpc-00e0a506e346cd668  
    AllowedValues:
         - ""
  
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet 1 ID  # <--- Replace with your subnet ID
  
  PublicSubnet2: 
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet 2 ID  # <--- Replace with your subnet ID

  GitHubRepo:
    Type: String 
    Description: URL of the public Git repository with the website template
    Default: https://github.com/abhisran/web_temp.git  # <--- You can change this default URL

Resources:

  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      VpcId: !Ref VPCId

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup  
    Properties:
      GroupDescription: Allow HTTP and SSH access
      VpcId: !Ref VPCId

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: my-alb
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: my-tg
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPCId

  WebServerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-abcd1234  # <--- Replace with your desired AMI ID
        InstanceType: t2.micro
        KeyName: !Ref KeyName
        SecurityGroupIds: 
          - !Ref WebServerSecurityGroup
        UserData:
          Fn::Base64: 
            !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd git
              systemctl start httpd
              systemctl enable httpd
              git clone ${GitHubRepo} /var/www/html

  WebServerGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref WebServerLaunchTemplate
        Version: !GetAtt WebServerLaunchTemplate.LatestVersionNumber
      MaxSize: 4
      MinSize: 2
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      TargetGroupARNs:
        - !Ref TargetGroup

Outputs:

  WebsiteURL:
    Description: URL of the website hosted on the ALB
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt LoadBalancer.DNSName
